Costmap 3D
BadgerTechnologies/navigation pull request #9
Opened 2019-10-23 19:29 UTC by c-andy-martin

The main body of this PR is adding a new costmap-3d package, which provides a 3D layered costmap based on octomaps. (Important Note: currently the badger-develop branch of octomap is required). The Costmap3DROS specializes Costmap2DROS to provide smooth backwards comparability. In order for that to work, the Costmap2DROS API was extended and ABI was broken (due to adding virtual keywords).

Since the Costmap3DROS is a Costmap2DROS, it has a 2D costmap associated with it. By default, this costmap will be empty. However, there is a pair of layer plugins which can be used to forward a flattened version of the 3D costmap to the corresponding 2D costmap, allowing easy migration into 3D navigation (so, for instance, some planners can be made to use the 3D costmap, while others continue to use the 2D costmap).

Several example costmap 3d plugins are provided, in addition to the previously mentioned 3D=>2D conversion layers. An octomap server layer is provided which subscribes to octomap updates from an octomap server. The corresponding octomap server can integrated many different sources of data (point clouds, laser scans). Also, a point cloud layer is provided which copies the last point cloud received into a costmap layer.

In addition to the 3D maps, the Costmap3DROS provides a direct querying interface in contrast to the 2D costmap. This query interface uses the badger-develop branch of FCL to perform queries against a robot mesh and the current costmap state. Four types of queries are provided, collision, cost, distance and signed distance, although not all are yet implemented.

2019-10-29 15:49 UTC, howardcochran requested changes
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 35 files at r6.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 10 of 48 files reviewed, 13 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_2d/include/costmap_2d/costmap_2d_ros.h, line 259 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIKFek307Na0vnRSiZ:-LsIKFek307Na0vnRSi_:b-4yx4vp) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/include/costmap_2d/costmap_2d_ros.h#L259)):*
> ```objc
> 
>   /** @brief Reset the costmap within the given axis-aligned bounding box in world coordinates across all layers. */
>   virtual void resetAABB(geometry_msgs::Point min, geometry_msgs::Point max);
> ```

I'm not a fan of the name "resetAABB".  Would prefer a name like retRegion, resetBox,.

However, if there is some existing convention for the use of "AABB' in this genre of practice that I am not familiar with, then I'm OK with it.
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 562 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsILAJ28EqAkQVaaeco:-LsILAJ28EqAkQVaaecp:bcw53rq) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L562)):*
> ```cpp
> 
>   std::vector < boost::shared_ptr<Layer> > *plugins = layered_costmap_->getPlugins();
>   for (vector<boost::shared_ptr<Layer> >::iterator plugin = plugins->begin(); plugin != plugins->end();
> ```

Just a style nit-pick: Is there a reason that range-based for wouldn't work here?  and/or the auto keyword in declaration of the iterator?
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 584 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIMNHF5Ts8BXb08ive:-LsIMNHF5Ts8BXb08ivf:b45miu4) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L584)):*
> ```cpp
>   {
>     // Only reset layers that are in the layer set
>     if (layers.find((*plugin)->getName()) != layers.end())
> ```

Should you add an else that does a warning about trying to clear a non-existent layer?
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 586 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIMCUc6-qodXcwzZl8:-LsIMCUc6-qodXcwzZl9:b-1z0t8) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L586)):*
> ```cpp
>     if (layers.find((*plugin)->getName()) != layers.end())
>     {
>       boost::shared_ptr<CostmapLayer> costmap_layer(boost::dynamic_pointer_cast<CostmapLayer>((*plugin)));
> ```

I see no problem here but have a question: What is a Layer that is not a CostmapLayer?  Maybe a warn_once, cuz I suppose it's possible that someone may want to make a static list of things to clear whether-or-not they are all actually present.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 69 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJ7RvJ5lEzY8PW0xAl:-LsJ7RvJ5lEzY8PW0xAm:b-iuyhu6) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L69)):*
> ```cpp
>   if (dsrv_)
>   {
>     delete dsrv_;
> ```

Please consider making this a shared pointer as you do in your other plugins.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 117 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJ8Uy7-w1mw0YiH-hR:-LsJ8Uy7-w1mw0YiH-hS:b-3ifcs5) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L117)):*
> ```cpp
>   super::resetMaps();
>   current_ = false;
>   layered_costmap_3d_ = NULL;
> ```

I have "memory leak" alarm bells going off in my head. It seems to me that this object stores this pointer whenever its ::updateFrom3D() is called. But I cannot find any caller to that method at all (in the navigation repo).  However, if that were true, the pointer would be uninitialized I think (the constructor does not appear to initialize it).  This would lead to a potential crash in updateBounds().  So, I'm confused - probably just missing something obvious.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 154 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJDByqDg8o4kAN31zh:-LsJDByqDg8o4kAN31zi:b780rtm) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L154)):*
> ```cpp
>       assert(max_map_y < (signed)size_y_);
>       for (int row = min_map_y; row <= max_map_y; ++row)
>       for (int row = min_map_y; row <= max_map_y; ++row)
> ```

Did you mean to duplicate this for() line?  Seems like this will make the body run N squared times.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 191 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJFe8D-MUCeTyr6IFX:-LsJFe8D-MUCeTyr6IFY:bbuwbbz) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L191)):*
> ```cpp
>         const int min_y_3d = (int)min_index_3d[1] - map_3d_oy;
>         const octomap::key_type depth_diff_3d = master_3d->getTreeDepth() - it.getDepth();
>         const octomap::key_type size_3d = (((octomap::key_type)1u)<<depth_diff_3d) - 1u;
> ```

OK.  So for leaf nodes, depth_diff_3d will be zero and inner body of the double-for loop below will only execute one time, right, right?  I'm having trouble picturing what all the compiler will optimize in this case, but I wonder whether it would be worth special-casing the leaf-node case for performance reasons?
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 253 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJGubQ6QcUO6yYYQqi:-LsJGubQ6QcUO6yYYQqj:bhfu7xv) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L253)):*
> ```cpp
>   while (it != end)
>   {
>     double half_size = it.getSize() / 2.0;
> ```

I don't see an issue here. But I don't understand what is going on with half_size.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJCGeDAZWi2h4dYJW5:-LsJCGeDAZWi2h4dYJW6:b-ncwpav) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp#L66)):*
> ```cpp
>   costmap_2d::LayeredCostmap* layered_costmap_2d = layered_costmap_3d_->getLayeredCostmap2D();
>   costmap_3d::Costmap3DTo2DLayer* layer_2d;
>   for (auto plugin_2d : *layered_costmap_2d->getPlugins())
> ```

How can you be sure that the Costmap3DTo2DLayer has been loaded yet?  Do we have a startup race / assumption about the order of plugin loading?
___
*[costmap_3d/plugins/point_cloud_layer_3d.cpp, line 108 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIjGF73PhI-S7vPudc:-LsIjGF73PhI-S7vPudd:b-tox3dv) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/point_cloud_layer_3d.cpp#L108)):*
> ```cpp
> {
>   // Find the global frame transform.
>   ros::Time stamp(pcl_conversions::fromPCL(cloud_msg->header.stamp));
> ```

I don't understand why ::fromPCL() is needed here. Isn't cloud_msg->header.stamp already a ros::Time?
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 67 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJJ0Jc2_X_WThiJiWW:-LsJJ0Jc2_X_WThiJiWX:b8y20uq) ([raw  [...]

2019-10-29 16:37 UTC, howardcochran commented
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 189 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNN9wu1MLQp9BC-PKi:-LsNN9wu1MLQp9BC-PKj:bfpgdue) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L189)):*
> ```objc
>       geometry_msgs::Pose rv;
>       // 1/4m
>       rv.position.x = std::round(pose.position.x * 4) / 4;
> ```

Should this constant (and the 8's and 1024's below) be either parameterized or at least declared as symbolic constants at the top of this file?


<!-- Sent from Reviewable.io -->

2019-10-29 21:50 UTC, c-andy-martin commented
___
*[costmap_2d/include/costmap_2d/costmap_2d_ros.h, line 259 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIKFek307Na0vnRSiZ:-LsOUCkuAcp0KnyA57IZ:bssq6cz) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/include/costmap_2d/costmap_2d_ros.h#L259)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I'm not a fan of the name "resetAABB".  Would prefer a name like retRegion, resetBox,.

However, if there is some existing convention for the use of "AABB' in this genre of practice that I am not familiar with, then I'm OK with it.
</blockquote></details>

AABB is a fairly common abbreviation for Axis-Aligned Bounding Box. Its used regularly in geometry libraries to distinguish w/ OBB (oriented bounding box, where its not axis aligned) and other types of bounding volumes. However, in this context, I think you are right that resetBoundingBox would unambiguously mean the same thing and be clearer, especially since I'm not using an object to represent the bounds. I think in general BoundingBox implies axis-aligned. I will make this change.


<!-- Sent from Reviewable.io -->

2019-10-29 21:52 UTC, c-andy-martin commented
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 562 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsILAJ28EqAkQVaaeco:-LsOVCBtAGSvE6D3T7aK:biaqppg) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L562)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Just a style nit-pick: Is there a reason that range-based for wouldn't work here?  and/or the auto keyword in declaration of the iterator?
</blockquote></details>

In the costmap_2d code, I'm following all of their conventions. I don't know that costmap_2d is compiled w/ c++11 support, for instance. I'd prefer to make it match the other costmap_2d code, so we can submit a PR upstream at some point.


<!-- Sent from Reviewable.io -->

2019-10-29 21:55 UTC, c-andy-martin commented
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 584 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIMNHF5Ts8BXb08ive:-LsOVoThE8gYmOfleUZ7:b40qe4e) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L584)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should you add an else that does a warning about trying to clear a non-existent layer?
</blockquote></details>

I don't think so, because you might conditionally include a layer in one config, and purposely make a super-set of all possible layer names you might want to clear, in which case you would expect some to be missing.


<!-- Sent from Reviewable.io -->

2019-10-29 21:55 UTC, c-andy-martin commented
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 586 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIMCUc6-qodXcwzZl8:-LsOVTXo-EBPz76NU4h8:bd8a94l) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/src/costmap_2d_ros.cpp#L586)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I see no problem here but have a question: What is a Layer that is not a CostmapLayer?  Maybe a warn_once, cuz I suppose it's possible that someone may want to make a static list of things to clear whether-or-not they are all actually present.
</blockquote></details>

I don't precisely know. In costmap_2d upstream, they have Layer which is the raw abstract interface and CostmapLayer which implements it (yet abstractly) and adds some extra costmap-related sutff. I suppose you could create a layer plugin where you don't want the extra costmap interfaces.


<!-- Sent from Reviewable.io -->

2019-10-30 19:41 UTC, howardcochran requested changes
> Reviewed 32 of 35 files at r6, 6 of 6 files at r7, 6 of 6 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: all files reviewed, 55 unresolved discussions (waiting on @c-andy-martin)

___
*[costmap_2d/src/costmap_2d_ros.cpp, line 561 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOHnb64oOj3A9doU3Q:-LsOHnb64oOj3A9doU3R:b-f8ug13) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_2d/src/costmap_2d_ros.cpp#L561)):*
> ```cpp
>   std::set<std::string> rv;
> 
>   std::vector < boost::shared_ptr<Layer> > *plugins = layered_costmap_->getPlugins();
> ```

It looks like we're going to iterate over the plugins without holding  `layered_costmap_`'s lock (which protects its addPlugin() method).  If our caller holds it, I have not found it in the code.
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 51 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNRbpo9UzV4f16wstd:-LsNRbpo9UzV4f16wste:b-59wa34) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L51)):*
> ```objc
> #include <tf2/utils.h>
> #include <costmap_3d/layered_costmap_3d.h>
> ```

According to https://en.cppreference.com/w/cpp/utility/hash, I think you need to #include <functional>
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 152 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO46grDR-yQsaC8y7u:-LsO46grDR-yQsaC8y7v:bwdhgxp) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L152)):*
> ```objc
>   using FCLRobotModelPtr = std::shared_ptr<FCLRobotModel>;
> 
>   FCLRobotModelPtr robot_model_;
> ```

I appreciate your use of smart pointers, but I wonder if, in some cases, such as `robot_model_`, you should just make the FCLRobotModel object itself be a member variable instead.  You only ever use its default constructor and then modify it, so I can see no reason why to use dynamic memory for it.

Originally, I thought I saw several smart pointers in this class for which the same could be said, but upon further examination, I think I see good reason for the others to be smart pointers rather than direct members.

But see comment in Costmap3DQuery::updateCompleteCallback()
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 205 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNOYR4CZzsmqW0V6mY:-LsNOYR4CZzsmqW0V6mZ:b-ajx0nr) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L205)):*
> ```objc
>       return rv;
>     }
>     inline geometry_msgs::Pose binPoseMicro(const geometry_msgs::Pose& pose)
> ```

Seems like binPose & binPoseMicro are good candidates for a template function where the two template parameters are double LinearResolution and double AngularResolution, with values such as 1/4.0 and 1/1024.0.
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 208 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNP1WS73ivZ7p-8A8g:-LsNP1WS73ivZ7p-8A8h:b-538fnd) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L208)):*
> ```objc
>     {
>       geometry_msgs::Pose rv;
>       // 1/4m
> ```

comment wrong
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 216 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNP3zh3yF5vddoe0IH:-LsNP3zh3yF5vddoe0II:b-pr2j23) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L216)):*
> ```objc
>       double yaw, pitch, roll;
>       tf2::getEulerYPR<geometry_msgs::Quaternion>(pose.orientation, yaw, pitch, roll);
>       // A 1/4 of a radian is about 14 degrees
> ```

Comment factually correct but confusing (should be 1/1024 radian)
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 278 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNqDe13Nc7OejlfAeS:-LsNqDe13Nc7OejlfAeT:bz0cttm) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L278)):*
> ```objc
>       octomap_box_tf = rhs.octomap_box_tf;
>       mesh_triangle = rhs.mesh_triangle;
> //      mesh_triangle_tf = rhs.mesh_triangle_tf;
> ```

Do you need to keep these commented out things?
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 329 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOMQ0J8gv6bInvIQV-:-LsOMQ0J8gv6bInvIQV0:b-4ca6pw) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L329)):*
> ```objc
> }  // namespace costmap_3d
> 
> #endif  // COSTMAP_3D_COSTMAP_3D_ROS_H
> ```

This comment should be COSTMAP_3D_COSTMAP_3D_QUERY_H_
___
*[costmap_3d/include/costmap_3d/costmap_3d_ros.h, line 251 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOMaIuCD2aLOSltXkA:-LsOMaIuCD2aLOSltXkB:bfjbjn2) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_ros.h#L251)):*
> ```objc
> }  // namespace costmap_3d
> 
> #endif  // COSTMAP_3D_COSTMAP_3D_ROS_H
> ```

This comment should be COSTMAP_3D_COSTMAP_3D_ROS_H_
___
*[costmap_3d/include/costmap_3d/octomap_server_layer_3d.h, line 90 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSD-k97XgIlwxuhg1:-LsOSD-k97XgIlwxuhg2:bqo3fyc) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/octomap_server_layer_3d.h#L90)):*
> ```objc
> 
>   ros::NodeHandle pnh_;
>   std::shared_ptr<dynamic_reconfigure::Server<costmap_3d::GenericPluginConfig>> dsrv_;
> ```

Candidate for direct member variable. The constructor's argument can be known at initializer list time.
___
*[costmap_3d/include/costmap_3d/point_cloud_layer_3d.h, line 81 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSsbgs3f66iQviBvoE:-LsSsbgs3f66iQviBvoF:bby8t0b) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/point_cloud_layer_3d.h#L81)):*
> ```objc
> 
>   ros::NodeHandle pnh_;
>   std::shared_ptr<dynamic_reconfigure::Server<costmap_3d::GenericPluginConfig>> dsrv_;
> ```

Make direct member?
___
*[costmap_3d/launch/example.launch, line 8 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSZxx4Qj384YSentm:-LsOSZxx4Qj384YSentn:bnhnh79) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example.launch#L8)):*
> ```XML
>   Also, if running from bagfiles, set the "use_sim_time" parameter to true
>   -->
>   <node name="costmap_node" pkg="costmap_3d" type="costmap_3d_node" output="screen"
> ```

Should the node_name not be costmap_3d_node (or just costmap_3d)?
___
*[costmap_3d/launch/example.launch, line 9 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSVk_Cmzzl9EL12qU:-LsOSVk_Cmzzl9EL12qV:b-k8vp69) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example.launch#L9)):*
> ```XML
>   -->
>   <node name="costmap_node" pkg="costmap_3d" type="costmap_3d_node" output="screen"
>   launch-prefix="gdb -ex run --args">
> ```

Probably don't want to check in this launch-prefix?
___
*[costmap_3d/launch/example.launch, line [...]

2019-10-30 19:41 UTC, howardcochran reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: all files reviewed, 55 unresolved discussions (waiting on @c-andy-martin)

___
*[costmap_2d/include/costmap_2d/costmap_2d_ros.h, line 259 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIKFek307Na0vnRSiZ:-LsTAxyg9YH62bzEgtCZ:b32w0x) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/include/costmap_2d/costmap_2d_ros.h#L259)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

AABB is a fairly common abbreviation for Axis-Aligned Bounding Box. Its used regularly in geometry libraries to distinguish w/ OBB (oriented bounding box, where its not axis aligned) and other types of bounding volumes. However, in this context, I think you are right that resetBoundingBox would unambiguously mean the same thing and be clearer, especially since I'm not using an object to represent the bounds. I think in general BoundingBox implies axis-aligned. I will make this change.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2019-10-31 20:39 UTC, c-andy-martin commented
___
*[costmap_2d/include/costmap_2d/costmap_2d_ros.h, line 259 at r2](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIKFek307Na0vnRSiZ:-LsYXimKCBh-t1wACS8G:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/beeba08b675db7d4d1adac509cdeb8fc6770aa03/costmap_2d/include/costmap_2d/costmap_2d_ros.h#L259)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-31 20:46 UTC, c-andy-martin commented
___
*[costmap_2d/src/costmap_2d_ros.cpp, line 561 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOHnb64oOj3A9doU3Q:-LsYYgdD1CKXGjrhcKbc:b3tyv0b) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_2d/src/costmap_2d_ros.cpp#L561)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

It looks like we're going to iterate over the plugins without holding  `layered_costmap_`'s lock (which protects its addPlugin() method).  If our caller holds it, I have not found it in the code.
</blockquote></details>

From examination, it appears to be illegal to call `addPlugin` outside of `Costmap2DROS` construction time. No one other than `Costmap2DROS` will have a way to reference the layered costmap until the `Costmap2DROS` constructor finishes. The existing code in `Costmap2DROS` does not lock the layered costmap while accessing its plugin list. Also, `addPlugin()` does not grab the lock either (so grabbing the lock won't synchronize with it anyway). So I *think* this is OK, as I don't want to make any changes to Costmap2DROS beyond what is necessary, since it is upstream code.


<!-- Sent from Reviewable.io -->

2019-10-31 20:49 UTC, c-andy-martin commented
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 51 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNRbpo9UzV4f16wstd:-LsYZwrmElmrgzZb1SmR:b3dhq0o) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L51)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

According to https://en.cppreference.com/w/cpp/utility/hash, I think you need to #include <functional>
</blockquote></details>

This is pulled in transitively by `unordered_map`, which uses `std::hash` in its interface


<!-- Sent from Reviewable.io -->

2019-10-31 20:52 UTC, c-andy-martin commented
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 152 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO46grDR-yQsaC8y7u:-LsY_jwqAY9V9OeBTKa_:b-nlje1h) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L152)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I appreciate your use of smart pointers, but I wonder if, in some cases, such as `robot_model_`, you should just make the FCLRobotModel object itself be a member variable instead.  You only ever use its default constructor and then modify it, so I can see no reason why to use dynamic memory for it.

Originally, I thought I saw several smart pointers in this class for which the same could be said, but upon further examination, I think I see good reason for the others to be smart pointers rather than direct members.

But see comment in Costmap3DQuery::updateCompleteCallback()
</blockquote></details>

The `FCL::CollisionObject` expects a `std::shared_ptr<CollisionGeometry<S>>`, so that's why I'm using shared_ptr here.


<!-- Sent from Reviewable.io -->

2019-11-01 16:16 UTC, c-andy-martin commented
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 189 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNN9wu1MLQp9BC-PKi:-LsbkCRQ3JrPbXhgCTdb:bb7f2mf) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L189)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should this constant (and the 8's and 1024's below) be either parameterized or at least declared as symbolic constants at the top of this file?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-11-01 16:17 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 32 of 50 files reviewed, 51 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 205 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNOYR4CZzsmqW0V6mY:-LsbkGBuEzzwzhwOcUYP:bsx7xqd) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L205)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Seems like binPose & binPoseMicro are good candidates for a template function where the two template parameters are double LinearResolution and double AngularResolution, with values such as 1/4.0 and 1/1024.0.
</blockquote></details>

OK, I did this w/ runtime parameters
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 208 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNP1WS73ivZ7p-8A8g:-LsbkJj9DEOS35bbFazQ:bb7f2mf) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L208)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

comment wrong
</blockquote></details>

done
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 216 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNP3zh3yF5vddoe0IH:-LsbkL-cB4NocKoGIhz2:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L216)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Comment factually correct but confusing (should be 1/1024 radian)
</blockquote></details>

Done.
___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 278 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNqDe13Nc7OejlfAeS:-LsbkMNLC2ugUm5CZ4k6:bb7f2mf) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L278)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Do you need to keep these commented out things?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2019-11-12 21:52 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 29 of 50 files reviewed, 49 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/include/costmap_3d/costmap_3d_query.h, line 329 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOMQ0J8gv6bInvIQV-:-LtWZMlm2nHyKhSumoQX:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_query.h#L329)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

This comment should be COSTMAP_3D_COSTMAP_3D_QUERY_H_
</blockquote></details>

Done.
___
*[costmap_3d/include/costmap_3d/costmap_3d_ros.h, line 251 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOMaIuCD2aLOSltXkA:-LtWZO8KDJMWd0Wtr_8c:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/costmap_3d_ros.h#L251)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

This comment should be COSTMAP_3D_COSTMAP_3D_ROS_H_
</blockquote></details>

Done.
___
*[costmap_3d/include/costmap_3d/octomap_server_layer_3d.h, line 90 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSD-k97XgIlwxuhg1:-LtW_En4816dwIdYiWSB:bwd52qb) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/octomap_server_layer_3d.h#L90)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Candidate for direct member variable. The constructor's argument can be known at initializer list time.
</blockquote></details>

Unless I'm missing something, I don't think I can know the NodeHandle at construction time, only at initialization time (which is later for the layer API). I think this needs to be dynamic
___
*[costmap_3d/include/costmap_3d/point_cloud_layer_3d.h, line 81 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSsbgs3f66iQviBvoE:-LtW_P3c2PRn7LDPLFXo:bi8fn3c) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/include/costmap_3d/point_cloud_layer_3d.h#L81)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Make direct member?
</blockquote></details>

I think I can't construct until I know the NodeHandle
___
*[costmap_3d/launch/example.launch, line 8 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSZxx4Qj384YSentm:-LtW_xrU7_UveTvJOdLS:b32w0x) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example.launch#L8)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should the node_name not be costmap_3d_node (or just costmap_3d)?
</blockquote></details>

OK
___
*[costmap_3d/launch/example.launch, line 9 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSVk_Cmzzl9EL12qU:-LtWa-9s8oklptFfY6_Q:b32w0x) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example.launch#L9)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Probably don't want to check in this launch-prefix?
</blockquote></details>

OK
___
*[costmap_3d/launch/example.launch, line 10 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOSlcU33qn07gQ7fzu:-LtWa0NkB8iv80yeZlF0:b-e9gmc3) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example.launch#L10)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

OK. I'm confused why the node name is costmap_node but the param namespace is different?

Also, do you want to load an overrides file here?
</blockquote></details>

The params need to be in a sub-namespace called `costmap` to follow the conventions used in move_base or mbf_costmap_nav. This is just an example of how to run a stand-alone costmap_3d_node for testing purposes


<!-- Sent from Reviewable.io -->

2019-11-12 21:55 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 28 of 50 files reviewed, 48 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/launch/example_params.yaml, line 33 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOTL1TEyLy7c5qNzK3:-LtWb7vk-hceaxf0_Rxf:b-bv65dz) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/launch/example_params.yaml#L33)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I am confused why you have two plugins: lists in this file, one without the octomap server, and one with it.
</blockquote></details>

Because, one plugin list is the 2D plugins, and the other is the 3D (its under costmap_3d)


<!-- Sent from Reviewable.io -->

2019-11-12 22:28 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 28 of 50 files reviewed, 47 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 117 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJ8Uy7-w1mw0YiH-hR:-LtWfzwO4G09DjXaMpY7:b9xkvn1) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L117)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I have "memory leak" alarm bells going off in my head. It seems to me that this object stores this pointer whenever its ::updateFrom3D() is called. But I cannot find any caller to that method at all (in the navigation repo).  However, if that were true, the pointer would be uninitialized I think (the constructor does not appear to initialize it).  This would lead to a potential crash in updateBounds().  So, I'm confused - probably just missing something obvious.
</blockquote></details>

This is set by `updateFrom3D` which is called by the companion 3D costmap layer that goes w/ this costmap_2d plugin.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 154 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJDByqDg8o4kAN31zh:-LtWgqiv7D-CYe_Q4JQI:b-yy10zm) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L154)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Did you mean to duplicate this for() line?  Seems like this will make the body run N squared times.
</blockquote></details>

good catch! done
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 191 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJFe8D-MUCeTyr6IFX:-LtWh46t-Z04UQGrzgTy:blg1dd4) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L191)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

OK.  So for leaf nodes, depth_diff_3d will be zero and inner body of the double-for loop below will only execute one time, right, right?  I'm having trouble picturing what all the compiler will optimize in this case, but I wonder whether it would be worth special-casing the leaf-node case for performance reasons?
</blockquote></details>

I think you mean for leaf nodes at the max depth. The loop is only iterating over leaf nodes, which can be at any depth, and the depth they are at determines their size. If a leaf node is not at the max depth, we need to render all the space it occupies. I don't think this is a performance critical path based on my profiling.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer.cpp, line 253 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJGubQ6QcUO6yYYQqi:-LtWhnHH0BORRvBeZkSF:b-dqwb6m) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer.cpp#L253)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I don't see an issue here. But I don't understand what is going on with half_size.
</blockquote></details>

Octomap cells x/y/z values are in the center of the cell. I need to find the boundaries in order to update the 2D bounds that have changed since the last map update. So, subtract/add half its width/height (which is getSize()) to find the bounds
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp, line 66 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJCGeDAZWi2h4dYJW5:-LtWiGeiCrhTShSCNa7v:bw0ao3l) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp#L66)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

How can you be sure that the Costmap3DTo2DLayer has been loaded yet?  Do we have a startup race / assumption about the order of plugin loading?
</blockquote></details>

all the 2d plugins are loaded and initialized before any 3d plugins. This is inherent in the design of layered costmap 3d, as you must pass it the corresponding (already constructed) 2d layered costmap.
___
*[costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp, line 87 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOTk-YE26unfUyujKv:-LtWiYcB8oHtrcty02YK:b-5moodj) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/costmap_3d_to_2d_layer_3d.cpp#L87)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should we hold a lock while iterating the plugin list?
</blockquote></details>

no, plugin lists are not dynamic and only setup once at construction time prior to this point.
___
*[costmap_3d/plugins/octomap_server_layer_3d.cpp, line 85 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOUDGK278pa56EWC1d:-LtWidlz6Ykj9HkICi28:b346bnj) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/octomap_server_layer_3d.cpp#L85)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I think this can be a direct member variable.
</blockquote></details>

I don't know the plugin name to make a node handle until init time (after construction), so I need to dynamic construct the dynamic reconfigure (I only saw constructors which took node handles)


<!-- Sent from Reviewable.io -->

2019-11-13 14:57 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 26 of 50 files reviewed, 46 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/plugins/octomap_server_layer_3d.cpp, line 112 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSSIT3Ars6lFzS3i5c:-Lt_7tXS4VrICa8X30bZ:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/octomap_server_layer_3d.cpp#L112)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I'm not sure if this matters, but it seems intuitive to me that the unsubscribe() should happen before super::deactivate().   That would be more consistent with your ::activate()
</blockquote></details>

Done.
___
*[costmap_3d/plugins/octomap_server_layer_3d.cpp, line 113 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSSH8iEht-yKIEyhMB:-Lt_7u0PC8rKcHZCmsZv:b-896fix) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/octomap_server_layer_3d.cpp#L113)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Useless comment
</blockquote></details>

Done.
___
*[costmap_3d/plugins/octomap_server_layer_3d.cpp, line 237 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSW74u4IKY-AZrDDRF:-Lt_80en1jL_zcUpErD0:b-e6icys) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/octomap_server_layer_3d.cpp#L237)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Here is a race:
```
Thread A                                   Thread B
::deactivate()
{
  unsubscribe()
  {
    lock_guard *this                  mapUpdateCallback()
                                      {
                                        lock_guard *this (blocked)
        unsubscribeUpdatesUnlocked()
  }  // *this unlocked)
}
                                        lock_guard *this returns
                                        if (seq number wrong)
                                        {
                                          unsubscribeUpdatesUnlocked();
                                          subscribeUpdatesUnlocked();
                                        }
                                      }
```

So, the final state is that we are subscribed to map updates even though we're deactivated.
In this scenario, it also unsubscribe to map updates when it has already been unsubscribed. I'm not sure whether that is OK or not.

</blockquote></details>

Good catch. I have changed layer locks to be recursive and hold the layer lock during all of activate/deactivate to synchronize them correctly, and added a new member variable, active_, to track whether we are active. The callbacks check if we are active after getting the lock, and if we have been deactivated, they do nothing, to handle the race where we may be about to process a message on one thread when we unsubscribe on another. Done.


<!-- Sent from Reviewable.io -->

2019-11-13 20:58 UTC, c-andy-martin commented
___
*[costmap_3d/plugins/point_cloud_layer_3d.cpp, line 83 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSo2ujEBGQTv3vsCEl:-LtaYQD6CbUlUQTqA1sk:b-6n8czs) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/point_cloud_layer_3d.cpp#L83)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

My intuition is that unsubscribe() should precede super::deactivate().  However, I don't think that is sufficient.  There is a race because unsubscribe() does not guarantee that the subscriber callback will not occur after it returns (it may already be queued). So it seems like this means you could deactivate the layer and then subsequently put new stuff onto the map from this layer. 

When a layer is deactivated, should the stuff from this layer be removed from the costmap?


</blockquote></details>

Good catch. I fixed this similar to the octomap server layer.


<!-- Sent from Reviewable.io -->

2019-11-13 20:59 UTC, c-andy-martin commented
___
*[costmap_3d/plugins/point_cloud_layer_3d.cpp, line 108 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsIjGF73PhI-S7vPudc:-LtaZ-5J2ohwFhRItZXi:bof0ikn) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/plugins/point_cloud_layer_3d.cpp#L108)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I don't understand why ::fromPCL() is needed here. Isn't cloud_msg->header.stamp already a ros::Time?
</blockquote></details>

no, CloudType will be a pcl::PointCloud<>


<!-- Sent from Reviewable.io -->

2019-11-14 22:35 UTC, c-andy-martin commented
___
*[costmap_3d/src/costmap_3d_query.cpp, line 122 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNvz2cE_k6sYpcra_Y:-Ltg2capCXgpWKNGfmE7:b-rsql9b) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L122)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Handle a "no such package" exception?
</blockquote></details>

oh, good catch. I made the query object print a ROS_ERROR on failure to initialize, and always return collisions on any query if there is no valid robot model loaded


<!-- Sent from Reviewable.io -->

2019-11-15 03:31 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 23 of 50 files reviewed, 41 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/src/costmap_3d_query.cpp, line 124 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNw1C0E55k_GSqXgWn:-Ltg2kfqCx1JOyePCcn2:b-ggjl39) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L124)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Handle a file not found, permissions, file contents malformed, or other I/O error?
</blockquote></details>

handled similar to no such package, done
___
*[costmap_3d/src/costmap_3d_query.cpp, line 128 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNwxGzEROLfygPkX3b:-Lth-kQKDrRnKGiPf8yh:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L128)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Seems like this is a good candidate for a separate function like:

    void padPointsSimple(const pcl::PointCloud<pcl::PointXYZ>&, std::vector<fcl::Vector3<FCLFloat>>*)

Could improve readability. 
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_query.cpp, line 140 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsNyNJ4E51hPB7rhFiG:-Lth-lDeCudAFj5wMQDD:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L140)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Another helper trianglesFromPolygons() ?
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_query.cpp, line 203 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO-iij2kLcH3FvGyYe:-Lth-q732b8HQZzqE7uW:b-udh76) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L203)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I have a feeling that the use of local smart pointers here just adds overhead (an extra inc & dec) that isn't necessary since you don't actually hold onto it beyond this function, and fcl::collide() just takes the raw pointers.
</blockquote></details>

FCL's API's take shared_ptr's to all the objects. this is OK
___
*[costmap_3d/src/costmap_3d_query.cpp, line 226 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO1F5BBs8JkeDC_PxG:-Lth3vjm27VTBoptAy21:bb7f2mf) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L226)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Perhaps the optimizer will do this for you, but you could make it explicit not to construct these objects if you get a micro-cache hit by moving these declarations below the following return statement.
</blockquote></details>

done
___
*[costmap_3d/src/costmap_3d_query.cpp, line 247 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO1xlT2b8NaVmU7DFt:-Lth5KaFAukLwe-fIBXC:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L247)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

So, it looks like, if the coarse cache is non-empty, that you are going to ask the first item in the cache for the distance to the new pose.  It is very unintuitive to me why you should do that (as opposed to asking any other cache entry the same thing).  Or just not doing this at all, since it looks, to me, like the subsequent `fcl::distance()`, is going to overwrite `result` anyway.

Perhaps a comment would help.
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_query.cpp, line 252 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO35OJ3ScUI4JFlFCL:-Lth5NbXEsYYpbZqe6fK:bw09qfv) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_query.cpp#L252)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should these constants be parameterized, or at least commented as to why these particular values are the right ones to use.?
</blockquote></details>

These actually are unneeded, FCL ignores them for the search we are doing, so I just removed setting them at all.


<!-- Sent from Reviewable.io -->

2019-11-15 22:21 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 22 of 50 files reviewed, 36 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/src/costmap_3d_ros.cpp, line 65 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO81I-82LRzZByUaw8:-Ltkd_HU3yh7mrlt9DVH:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L65)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

It appears, to me, that layered_costmap_3d_ is a candidate for being a direct member rather than a smart pointer with dynamic allocation.

Not sure if you agree with this, but I like to avoid using dynamic memory whenever it is not needed. It is not needed when:
1. There is only ever one of them created
2. It uses its default constructor
3. OR, (as in this case), the argument to its constructor is known early enough to use it in the initializer list for this constructor.

In some cases when it would otherwise be needed, it can be made not to be needed by using an initialize() method to populate required data after construction. I like to do this to avoid dynamic allocations when I own the objects and when doing so does not add undue overhead.

In any case, feel free to disagree, but I will point out some other candidates for avoiding `new` in this review.

</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 67 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJJ0Jc2_X_WThiJiWW:-LtkpRluCGoGaBNqdTfM:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L67)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Is it strictly necessary to call hasParam here?  Theoretically, the parameter could cease to exist after hasParam returns true but before getParam is called a couple of lines later.
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 77 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJK9AUEFj2r6pMAlRu:-LtkpSZQ-2s9Hs7W6TSm:b-79xyid) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L77)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

What if this plugin type is not found by the loader?  Will plugin be nullptr?  If so, then it crashes.
</blockquote></details>

Fixed. Done.
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 83 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsO9YfJ3WMPB2-t3pUF:-LtkpUOG5SUSMBIit4SL:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L83)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

publisher_ could be a direct member variable if the guts of its contructor were moved into an initialize() method. It's somewhat of a toss-up whether that is warranted.
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 85 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOBwYV8MjaLMKBjrL3:-LtkpVQS2O0hyKnmTZwj:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L85)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Candidate for direct member variable.  The `name` used here is known during the initializer list.
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 92 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOBmSB49ENdzgqBVWE:-LtkpX8ZDAfBAxZ2jofm:bb6un1j) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L92)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

This is a candidate for direct member variable. In fact the ROS tutorial uses it that way. 
</blockquote></details>

Done
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 98 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJOiDP63y0WgfVpn-D:-LtksYgp4KGNE8NiDYO-:b-lgl0j1) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L98)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

So it seems a little weird that this service or action can be called prior to setting initialized_ to true just below, especially since the servers do not acquire initialized_mutex_.  AFAICT, nothing bad will actually happen here if initialized_ is still false, but I'm not 100% sure.
</blockquote></details>

I moved initialized up and drop the lock before publishing, as at this point the object really is all the way initialized.
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 115 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOEzWy96G7DIS7TyWB:-LtktOJV6guGZkAHJR25:b-d39edf) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L115)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I think that we need a config_lock_ here, or maybe we just need to grab layered_costmap_3d_'s lock here.  This function can run concurrently with the query action or service, which locks the costmap while this function calls setBounds & setResolution on it unlocked.

EDIT: I see now that setBounds and setReslution grab the lock internally.  So, I think the worst that can happen is that we could run a query service while a dynamic reconfigure has only partially been applied.  That's not catastrophic, but I still prefer making a `config_mutex_`


</blockquote></details>

I have re-architected this due to some of the below comments. Now there is just one call to setBounds(). This should now be OK
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 131 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsJRCDx9DA2S28wPx8g:-Ltl2N5bCRLem9BW_1iG:bh98b0n) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L131)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

In practice, how does the 2D costmap size get set before we get here?  Particularly for a non-rolling map, where I think that size may depend on the size of the static map. In that case, how can we be sure that that layer has been loaded yet?  What if it were to change in the future (e.g. static map update)?  I don't think that would guarantee that this reconfigure function gets called again, would it?

Even for a rolling map, the 2D map theoretically allows the size of it to be changed by a dynamic reconfigure.
</blockquote></details>

Um...it doesn't. This was a bug. I have re-architected as follows:
Costmap3DROS simply sets the Z bounds of LayeredCostmap3D on dynamic reconfigure
LayeredCostmap3D will match the resolution and 2D dimensions of the costmap on every updateMap cycle (and
will do the same when setting Z bounds).
It is no longer possible to set the resolution or X/Y bounds of the LayeredCostmap3D to be different from the LayeredCostmap2D resolution or X/Y bounds.
Let me know if this is OK
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 168 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOGbpo2rXBTviyyD0V:-Ltl66XM7C93DlGE5Fxk:bykfzzc) ([raw file](https://github.com/badgert [...]

2019-11-18 15:17 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 21 of 50 files reviewed, 36 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/src/costmap_layer_3d.cpp, line 56 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsStfoQ5j60HTx14yfM:-Ltz3Qp-2grguUkN33wH:b-mve54c) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_layer_3d.cpp#L56)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should we `&& enabled_` here like ::updateCosts() does?
</blockquote></details>

I'm following costmap_2d's since of `enabled_`, which really means something like "keep track of changes but don't copy your layer to the costmap". I need to update the bounds_map with the whole costmap when going from `enabled_ = true` to `enabled_ = false` so the other layers paint their data after I've been disabled, and the same thing when going the other direction. What I don't need to do is alter the bounds after that. This is why `touch()` doesn't alter the `changed_cells_` while disabled, so there are no changes to apply except while disabled in steady state. When we are reenabled, we touch the whole map, so all cells have changed.
___
*[costmap_3d/src/costmap_layer_3d.cpp, line 92 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSttx5DoD1785Cu2vE:-Ltz4JdmEHnM2oEmpeb_:bifey0s) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_layer_3d.cpp#L92)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Suggest WARN Level instead of INFO
</blockquote></details>

I'm thinking there may be cases where this will be the intended behavior. I haven't been able to think of a good one yet, but that was why I left it INFO and just printed it once.
___
*[costmap_3d/src/costmap_layer_3d.cpp, line 113 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsSu3Ww7S6HOQ48ZZ6i:-Ltz4czx8r2Qx7E5Tqpb:b-jcf5iq) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_layer_3d.cpp#L113)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

I'm confused that the implementation of this is identical to that of ::activate, while the comment suggests that they do opposite things.
</blockquote></details>

touching just means that the cells have changed. They have (virtually) by way of either being disabled or enabled. In either case, I need the bounds map of the next update to have every cell of this layer in it, so in the case of being disabled, all other layers have an opportunity to copy their data, or in the case of being enabled, this layer has an opportunity to copy its data.


<!-- Sent from Reviewable.io -->

2019-11-18 15:22 UTC, c-andy-martin reviewed
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: 21 of 50 files reviewed, 36 unresolved discussions (waiting on @c-andy-martin and @howardcochran)

___
*[costmap_3d/src/layered_costmap_3d.cpp, line 186 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOH2ix033yOq7HSuTu:-Ltz5OAS6yIDUV92mCSr:b-4lpkz7) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/layered_costmap_3d.cpp#L186)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should you lock_guard `this` as you do in ::reset() above?
</blockquote></details>

I'm following the design of costmap_2d here. The costmap is not internally locked by activate/deactivate (called by start/stop on the costmap_2d_ros). If that is necessary for the layered costmap, the caller of start/stop must synchronize. But it is OK to call start/stop w/out locking as long as the caller guarantees they aren't called simultaneously (which move_base does). Its not OK for the layers to mess their layers up in this state, which is one reason the 3D layers have their own locks, which they do grab if they are going to modify their state that's shared w/ the updateMap APIs.
___
*[costmap_3d/src/layered_costmap_3d.cpp, line 194 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOHDVO-LLbYiKDjuKb:-Ltz5osN78NF7qntH6kj:bqw7jiq) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/layered_costmap_3d.cpp#L194)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Should you lock_guard `this` as you do in ::reset() above?
</blockquote></details>

See the comment on activate


<!-- Sent from Reviewable.io -->

2019-12-02 17:55 UTC, howardcochran commented
___
*[costmap_3d/src/costmap_3d_ros.cpp, line 239 at r6](https://reviewable.io/reviews/badgertechnologies/navigation/9#-LsOOu0W2e1puPkvQNcK:-Lv6gZv_7vsqiYqX9DmR:biiazis) ([raw file](https://github.com/badgertechnologies/navigation/blob/5a656ba3f32a1e6c3619ccccb929ed4d30183783/costmap_3d/src/costmap_3d_ros.cpp#L239)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

For a workload where someone is calling footprintCost externally a lot, getQuery is in the fast path. So I designed this to do as few copies of the string as possible. getFootprintMeshResource is a private method for internal class use only, and I wanted it not to copy anything. Is that OK?
</blockquote></details>

Yes. Thanks for that explanation.


<!-- Sent from Reviewable.io -->

2019-12-02 17:56 UTC, howardcochran commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2019-12-02 17:58 UTC, howardcochran approved these changes
> Reviewed 30 of 30 files at r10.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/navigation/9)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-01-14 01:15 UTC, merged